image: "rust:latest"
fdsfsafaf".dsa
test:
   script:
        - rustc --version && cargo --version
        - cargo test --workspace --verbose

build:
    script:
        - cargo build --release
    artifacts:
        paths:
            - target/release/app
